name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"


jobs:
  unix:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Oldest supported versions
          - name: Linux (CUDA 10.2, Python 3.7, PyTorch 1.7)
            os: ubuntu-18.04
            cuda-version: "10.2.89"
            gcc-version: "9.4.*"
            nvcc-version: "10.2"
            python-version: "3.7"
            pytorch-version: "1.7.*"
            CMAKE_FLAGS: |
              -DNN_BUILD_CUDA_LIB=ON \
              -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
              -DEXTRA_COMPILE_FLAGS="-L/usr/local/cuda/lib64/stubs -Wl,-rpath,/usr/local/cuda/lib64/stubs -Wl,-rpath-link,/usr/local/cuda/lib64/stubs"

          # Latest supported versions
          - name: Linux (CUDA 11.2, Python 3.9, PyTorch 1.10)
            os: ubuntu-18.04
            cuda-version: "11.2.2"
            gcc-version: "11.2.*"
            nvcc-version: "11.2"
            python-version: "3.9"
            pytorch-version: "1.10.*"
            CMAKE_FLAGS: |
              -DNN_BUILD_CUDA_LIB=ON \
              -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda \
              -DEXTRA_COMPILE_FLAGS="-L/usr/local/cuda/lib64/stubs -Wl,-rpath,/usr/local/cuda/lib64/stubs -Wl,-rpath-link,/usr/local/cuda/lib64/stubs"


          - name: MacOS (Python 3.9, PyTorch 1.10)
            os: macos-11
            python-version: "3.9"
            CMAKE_FLAGS: ""


    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: "Install CUDA Toolkit on Linux (if needed)"
        uses: Jimver/cuda-toolkit@v0.2.5
        with:
          cuda: ${{ matrix.cuda-version }}
        if: startsWith(matrix.os, 'ubuntu')

      - name: "Install SDK on MacOS (if needed)"
        run: source devtools/scripts/install_macos_sdk.sh
        if: startsWith(matrix.os, 'macos')

      - name: "Update the conda enviroment file (if needed)"
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sed -i -e "s/@CUDATOOLKIT_VERSION@/${{ matrix.cuda-version }}/g" \
                 -e "s/@GCC_VERSION@/${{ matrix.gcc-version }}/g" \
                 -e "s/@NVCC_VERSION@/${{ matrix.nvcc-version }}/g" \
                 -e "s/@PYTORCH_VERSION@/${{ matrix.pytorch-version }}/g" \
                 devtools/conda-envs/build-${{ matrix.os }}.yml

      - uses: conda-incubator/setup-miniconda@v2
        name: "Install dependencies with conda"
        with:
          activate-environment: build
          environment-file: devtools/conda-envs/build-${{ matrix.os }}.yml
          python-version: ${{ matrix.python-version }}

      - name: "List conda packages"
        shell: bash -l {0}
        run: conda list

      - name: "Configure"
        shell: bash -l {0}
        run: |
          mkdir build
          cd build

          SHLIB_EXT=".so"
          if [[ ${{ matrix.os }} == macos-* ]]; then
            SHLIB_EXT=".dylib"
          fi

          cmake .. \
            -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
            -DCMAKE_PREFIX_PATH=${CONDA_PREFIX} \
            -DCMAKE_BUILD_TYPE=Release \
            -DOPENMM_DIR=${CONDA_PREFIX} \
            -DPYTORCH_DIR=${CONDA_PREFIX}/lib/python${{ matrix.python-version }}/site-packages/torch \
            -DTorch_DIR=${CONDA_PREFIX}/lib/python${{ matrix.python-version }}/site-packages/torch/share/cmake/Torch \
            -DNN_BUILD_OPENCL_LIB=ON \
            -DOPENCL_INCLUDE_DIR=${CONDA_PREFIX}/include \
            -DOPENCL_LIBRARY=${CONDA_PREFIX}/lib/libOpenCL${SHLIB_EXT} \
            ${{ matrix.CMAKE_FLAGS }}

      - name: "Build"
        shell: bash -l {0}
        run: |
          cd build
          make -j2 install
          make -j2 PythonInstall

      - name: "List plugins"
        shell: bash -l {0}
        run: |
          export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib/python${{ matrix.python-version }}/site-packages/torch/lib:${LD_LIBRARY_PATH}"
          python -c "import openmm as mm; print('---Loaded---', *mm.pluginLoadedLibNames, '---Failed---', *mm.Platform.getPluginLoadFailures(), sep='\n')"

      - name: "Run C++ test"
        shell: bash -l {0}
        run: |
          export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib/python${{ matrix.python-version }}/site-packages/torch/lib:${LD_LIBRARY_PATH}"
          cd build
          ctest --output-on-failure --exclude-regex TestCuda

      - name: "Run Python test"
        shell: bash -l {0}
        run: |
          export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib/python${{ matrix.python-version }}/site-packages/torch/lib:${LD_LIBRARY_PATH}"
          cd python/tests
          pytest --verbose Test*
